filetype on
set number
set tabstop=4
set shiftwidth=4
set textwidth=80

" to undo auto indent: set noautoindent
set autoindent
set smartindent
set cindent

"Hitting arrow keys adds characters is fixed by set nocompatible
set nocompatible

"fixing backspace 
set backspace=indent,eol,start

syntax on

colorscheme desert
